---
name: POE-Filter-XML
version: 0.35
author: []
abstract: A POE Filter for parsing XML
license: gpl
resources:
  license: http://opensource.org/licenses/gpl-license.php
requires:
  Class::InsideOut: 1.09
  Filter::Template: 1.02
  POE: 1.003
  XML::LibXML: 1.69
  XML::SAX: 0.16
  perl: 5.10.0
provides:
  POE::Filter::XML:
    file: lib/POE/Filter/XML.pm
    version: 0.35
  POE::Filter::XML::Handler:
    file: lib/POE/Filter/XML/Handler.pm
    version: 0.35
  POE::Filter::XML::NS:
    file: lib/POE/Filter/XML/NS.pm
    version: 0.35
  POE::Filter::XML::Node:
    file: lib/POE/Filter/XML/Node.pm
    version: 0.35
  POE::Filter::XML::Utils:
    file: lib/POE/Filter/XML/Utils.pm
    version: 0.35
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
